// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

namespace LottoML_net6
{
    public partial class _655_slot6
    {
        /// <summary>
        /// model input class for _655_slot6.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"sorted6")]
            public float Sorted6 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for _655_slot6.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"sorted6")]
            public float[] Sorted6 { get; set; }

            [ColumnName(@"sorted6_LB")]
            public float[] Sorted6_LB { get; set; }

            [ColumnName(@"sorted6_UB")]
            public float[] Sorted6_UB { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"G:\projects\loabletech\LottoML.net\LottoML.net6\655-slot6.zip");

        public static readonly Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput? input = null, int? horizon = null)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input, horizon);
        }

        private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
            return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
        }
    }
}

